# Generated by Django 5.0 on 2024-02-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=10, null=True)),
                ('client_name', models.CharField(blank=True, max_length=10, null=True)),
                ('project_date', models.CharField(blank=True, max_length=10, null=True)),
                ('main_text', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_text', models.CharField(blank=True, max_length=100, null=True)),
                ('labelimg', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('subimg1', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('subimg2', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('subimg3', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('subimg4', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('endimg1', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('endimg2', models.ImageField(blank=True, null=True, upload_to='images/uploads/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
