# Generated by Django 5.0 on 2024-02-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_projects_main_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='sub_text',
            new_name='sub_text1',
        ),
        migrations.AddField(
            model_name='projects',
            name='sub_text2',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
