# Generated by Django 5.0 on 2024-02-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_sub_text_projects_sub_text1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='main_text',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='sub_text1',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='sub_text2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
