# Generated by Django 5.0 on 2024-02-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
