# Generated by Django 5.0 on 2024-02-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=80, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
