# Generated by Django 5.0 on 2024-02-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_customer_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
