# Generated by Django 5.0 on 2024-03-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True)),
                ('calendely', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
