# Generated by Django 5.0 on 2024-09-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_social_links'),
    ]

    operations = [
        migrations.DeleteModel(
            name='social_links',
        ),
    ]
